
list1 = []
print('请输入ID(如 1001):')
ID = input()
print('请输入名字:')
name = input()
list2 = []
print('请输入英语成绩:')
score1 = int(input())
print('请输入Python成绩:')
score2 = int(input())
print('请输入C语言成绩:')
score3 = int(input())
print('学生信息录入完毕!!!')
list1.append(ID)
list1.append(name)
list1.append(score1)
list1.append(score2)
list1.append(score3)
list2.append(score1)
list2.append(score2)
list2.append(score3)
print('封装的列表是:')
print(list1)
print('总分:', sum(list2), ',', '平均分是:', round(sum(list2)/len(list2), 2), sep='')
